apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shift-scheduling
data:
  MONGODB_URL: "mongodb://mongodb:27017"
  KAFKA_BROKER: "kafka:9092"
  NODE_ENV: "production"
  ALERTES_SERVICE: "alertes:50051"
  EMPLOYEE_SERVICE: "employee:50053"
  JOBPLANNING_SERVICE: "jobplanning:50052"

